name: Azure Static Web Apps CI/CD

env:
  APP_LOCATION: "/Web/reeinvent-wordify-web"

on:
  push:
    branches:
      - main
      
jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_RED_SKY_0BD84C803 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "${{ env.APP_LOCATION }}"
          output_location: "build"
