name: Build and deploy a container to an Azure Web App

env:
  AZURE_WEBAPP_NAME: reeinvent-wordify
  AZURE_WEBAPP_PACKAGE_PATH: "./publish"

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  publish: 
    runs-on: ubuntu-latest
    
    steps: 
      - uses: actions/checkout@v3
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with: 
          dotnet-version: '6.0.x'
          
      - name: Restore Packages
        run: dotnet restore ./Services/Wordify/Reeinvent.Wordify.API/Reeinvent.Wordify.API.csproj
        
      - name: Build
        run: dotnet build ./Services/Wordify/Reeinvent.Wordify.API/Reeinvent.Wordify.API.csproj --configuration Release --no-restore
        
      - name: Publish
        run: dotnet publish ./Services/Wordify/Reeinvent.Wordify.API/Reeinvent.Wordify.API.csproj --configuration Release --no-build '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}'
        
      - name: Deployment
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}"
