name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
      
jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
        env:
          REACT_APP_API_URL: ${{ secrets.REACT_APP_WORDIFY_API }}
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_RED_SKY_0BD84C803 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/Web/reeinvent-wordify-web"
          output_location: "build"
